backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# This line should *not* be indented
#publish_mode: editorial_workflow
# This line should *not* be indented -- needed if users are allowed to upload images - set to images directory
# These two lines are needed for Hugo sites
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "sweetFrog Fayetteville Towne Center, NY"
        name: "index"
        file: "content/index.md"
        fields:
          - {label: Title, name: title}

